export const ADD_PROJECT = 'PROJECT_ACTION:ADD_PROJECT';
export const EDIT_PROJECTT_NAME = 'PROJECT_ACTION:EDIT_PROJECTT_NAME';
export const UPDATE_PROJECT_NAME = 'PROJECT_ACTION:UPDATE_PROJECT_NAME';
